### ISSUE TITLE
startup error METEOR@1.6.0.1

### ISSUE THREAD

**Issue by hexsprite** [qualialabs/profile#1]
```
   While loading plugin `qualia:profile` from package `qualia:profile`:
   packages/qualia_profile_plugin.js:153:9: Package._define is not a function
   at packages/qualia_profile_plugin.js:153:9
   at packages/qualia_profile_plugin.js:155:3
```

**Comment by hexsprite** [comment]
FYI I tried a `meteor reset`, also tried fully removing my Meteor installation and re-installing all packages.

**Comment by hexsprite** [comment]
I was able to get it to start by cloning into my `packages/` directory. Not sure what's up with the published package.

**Comment by hexsprite** [comment]
https://github.com/meteor/meteor/issues/9700

fixed with: `meteor add meteor@=1.8.4`

meteor package was at 1.8.6 previously

**Comment by hexsprite** [comment]
still having the same problem actually. It seems like a hot-reload will allow one to proceed when this error comes up. I added some debugging statements and it seems like `Package` is `{}` at the time of execution...

**Comment by veered** [comment]
I'll take a look this week

**Comment by veered** [comment]
I'm not able to replicate this issue. Could you please create a reproduction?

**Comment by hexsprite** [comment]
Sure...

'https://github.com/hexsprite/qualia-profile-issue-1

```
➜  qualia-profile-issue-1 git:(master) npm start

> qualia-profile-issue-1@ start /Users/jbb/co/qualia-profile-issue-1
> meteor run

[[[[[ ~/co/qualia-profile-issue-1 ]]]]]       

=> Started proxy.                             
{} Determining active plugins                |
=> Errors prevented startup:                  
   
   While loading plugin `qualia:profile` from package `qualia:profile`:
   packages/qualia_profile_plugin.js:154:9: Package._define is not a function
   at packages/qualia_profile_plugin.js:154:9
   at packages/qualia_profile_plugin.js:156:3
   
   
=> Your application has errors. Waiting for file change.
=> A patch (Meteor 1.6.1.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
```

**Comment by veered** [comment]
Ok, looks like this is related to a general bug in older versions of Meteor. See https://github.com/meteor/meteor/issues/9695#issuecomment-370192987

If you update to a more recent version of Meteor `1.6` (by running `meteor update --patch`), I was able to get your reproduction running fine.

**Comment by hexsprite** [comment]
Thanks for looking into it. Unfortunately I can't update beyond 1.6.0.x at this time due to some of the major changes in 1.6.1. Guess I'll just survive without this profile package at this time and depend on the v8 dependencies directly.

**Comment by veered** [comment]
Out of curiosity, what changes are preventing you from upgrading?

**Comment by hexsprite** [comment]
it's a good question. a lot of it is related to dependencies that were using the old version of coffeescript and haven't yet made the upgrade yet. and some had to do with some incompatibilities of packages with newer versions of mitar's packages. I think it's solvable when I have some more time... ;)
