### ISSUE TITLE
Does not install on Windows

### ISSUE THREAD

**Issue by KoenLav** [qualialabs/profile#2]
`
While loading qualia:profile@0.0.8...:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild --update-binary
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.7 and node@8.11.3 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build"
"--module=C:\\Users\\koenl\\AppData\\Local\\Temp\\mt-2a329y.u4sxp\\plugin.qualia_profile.os\\npm\\node_modules\\meteor\\qualia_profile\\node_modules\\.temp-q5ifvt.pe0z9\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.7\\node-v57-win32-x64\\profiler.node" "--module_name=profiler"
"--module_path=C:\\Users\\koenl\\AppData\\Local\\Temp\\mt-2a329y.u4sxp\\plugin.qualia_profile.os\\npm\\node_modules\\meteor\\qualia_profile\\node_modules\\.temp-q5ifvt.pe0z9\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.7\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\bin\node.exe
C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build
--module=C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64\profiler.node --module_name=profiler
--module_path=C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koenl\AppData\Roaming\npm-cache\_logs\2018-07-17T13_03_13_017Z-debug.log
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-node8@5.7.7 and node@8.11.3 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build"
"--module=C:\\Users\\koenl\\AppData\\Local\\Temp\\mt-2a329y.u4sxp\\plugin.qualia_profile.os\\npm\\node_modules\\meteor\\qualia_profile\\node_modules\\.temp-q5ifvt.pe0z9\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.7\\node-v57-win32-x64\\profiler.node" "--module_name=profiler"
"--module_path=C:\\Users\\koenl\\AppData\\Local\\Temp\\mt-2a329y.u4sxp\\plugin.qualia_profile.os\\npm\\node_modules\\meteor\\qualia_profile\\node_modules\\.temp-q5ifvt.pe0z9\\node_modules\\v8-profiler-node8\\build\\profiler\\v5.7.7\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\bin\node.exe
C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build
--module=C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64\profiler.node --module_name=profiler
--module_path=C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8\build\profiler\v5.7.7\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\koenl\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\koenl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.7.0_3\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\koenl\AppData\Local\Temp\mt-2a329y.u4sxp\plugin.qualia_profile.os\npm\node_modules\meteor\qualia_profile\node_modules\.temp-q5ifvt.pe0z9\node_modules\v8-profiler-node8
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by veered** [comment]
So looks like the v8 profiler failed to build? Are you able to install the v8 profiler (by listing it in a package with in a barebones Meteor project (you'll have to add it as a Meteor package and add the dependency like https://github.com/qualialabs/profile/blob/master/package.js#L22)?

Also worth testing whether or not `meteor npm install v8-profiler-node8` fails

**Comment by KoenLav** [comment]
meteor npm install v8-profiler-node8; no problem.

Npm.depends({
  'v8-profiler-node8': "5.7.7",
});

Also seems to work...

I'll try again.

**Comment by KoenLav** [comment]
@veered while installing the profiler directly, or importing it from another package, all seems to work fine.

But installing your package ends up with this error every time.

I'll try forking it and updating the v8-profiler to 6.0.0.

**Comment by KoenLav** [comment]
Yeah, that fixes things.

I was able to successfully create a profile from the meteor shell as well.

**Comment by veered** [comment]
Fixed in 69bd0b2e9163d9fcbe9e9b598d43b1aa72fa874f
