### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open

### ISSUE THREAD

**Issue by yogeshwar607** [qualialabs/profile#5]
Getting below issue on mac when running through meteor shell

    `import Profiler from "meteor/qualia:profile";
      let profileName = 'myprofile';
      let profilePath = `/Users/yogi/frontier/fm.client.meteor.updated/.profile`;
      let profileMS = 10000;

    Profiler.profileDuration(profileName, profilePath, profileMS);

> Error: EISDIR: illegal operation on a directory, open`

**Comment by veered** [comment]
Is `/Users/yogi/frontier/fm.client.meteor.updated/.profile` a directory? Perhaps you actually want `/Users/yogi/frontier/fm.client.meteor.updated/.profile/mycpuprofile.cpuprofile`.

That's what this StackOverflow post says `EISDIR` means:
https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a
