### ISSUE TITLE
Flamechart image in readme broken

### ISSUE THREAD

**Issue by TechplexEngineer** [qualialabs/profile#6]

**Comment by veered** [comment]
Fixed

**Comment by veered** [comment]
I think I might need to leave this image here so the URL won't expire:

<img width="1160" alt="Screen Shot 2018-04-21 at 5 18 44 PM" src="https://user-images.githubusercontent.com/247408/60747657-a0bae300-9f3b-11e9-8dc3-b615a2611aca.png">
